#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES — the provisioning steps only a human can take (phase 2 ticket 07).
#
# Everything else in phase 2 is scripted somewhere else: ticket 05 owns nginx
# and the release directories on the VPS, ticket 18 owns building and signing
# the Android artifacts. What is left over is what this file walks - a DNS
# record, a hosting account, a store registration, a signing key - and none of
# it can be done by anything that is not a person with a browser and a card.
#
# Three rules the stages hold to:
#   - Say what a value is for, and what will read it, before asking for it.
#   - Nothing is written into this repository. It is public, and half of what
#     gets captured here is a credential.
#   - A second run costs nothing. Provisioning spans days, because a Play
#     account has to be verified by Google before it can hold an app.
#
# Read it before you run it: DRY_RUN=1 scripts/provision.sh performs nothing
# and describes every step it would have taken.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

DRY_RUN="${DRY_RUN:-0}"

# ── What this is provisioning, read rather than repeated ───────────────────

ADR="docs/adr/0019-the-landing-site-and-journal-use-separate-origins.md"
RELEASE_WORKFLOW=".github/workflows/release.yml"
if [[ ! -f "$ADR" || ! -f "$RELEASE_WORKFLOW" ]]; then
  printf 'Run this from the repository root. It reads %s and %s.\n' \
    "$ADR" "$RELEASE_WORKFLOW" >&2
  exit 1
fi

# The two origins and the application ID are decided (ticket 01), and the ADR's
# "The values" section is the committed record of them. Read from there, because
# a wizard holding its own copy is a wizard that can walk you through setting up
# an origin the app does not live on - and the Journal's origin is the one value
# that cannot be moved once somebody has stored a Journal on it.
adr_value() { sed -n "s/^- $1: \`\([^\`]*\)\`.*$/\1/p" "$ADR" | head -n1; }
JOURNAL_ORIGIN=$(adr_value "Journal")
LANDING_ORIGIN=$(adr_value "Landing site")
ANDROID_APP_ID=$(adr_value "Android application ID")
for _name in JOURNAL_ORIGIN LANDING_ORIGIN ANDROID_APP_ID; do
  [[ -n "${!_name}" ]] || {
    printf 'Could not read %s out of %s: the "The values" section has changed shape.\n' \
      "$_name" "$ADR" >&2
    exit 1
  }
done

# And the environment name from the workflow that reads the secrets, so filling
# a differently named environment cannot look like success.
RELEASE_ENV=$(sed -n 's/^ *environment: *\([A-Za-z0-9_-]*\) *$/\1/p' "$RELEASE_WORKFLOW" | head -n1)
[[ -n "$RELEASE_ENV" ]] || {
  printf 'Could not read the environment name out of %s.\n' "$RELEASE_WORKFLOW" >&2
  exit 1
}

REPO_DEFAULT=$(git config --get remote.origin.url 2>/dev/null |
  sed -e 's#\.git$##' -e 's#^.*[:/]\([^/]*/[^/]*\)$#\1#') || true
LANDING_REPO_DEFAULT="${REPO_DEFAULT%/*}/gender-diary-landing"
VPS_ALIAS="${GENDER_DIARY_VPS_ALIAS:-zabka-vps}"

# ── Where the captured values go ───────────────────────────────────────────
#
# Outside the repository, under the user's own state directory. The two files
# hold hostnames, usernames and which stages finished. No secret reaches either
# of them: a secret goes to the protected environment on GitHub, or to the
# wallet, and nowhere a backup or a `git add -A` can pick it up.

if (( DRY_RUN )); then
  STATE_DIR="${GENDER_DIARY_STATE_DIR:-$(mktemp -d)}"
else
  STATE_DIR="${GENDER_DIARY_STATE_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/gender-diary}"
fi
mkdir -p "$STATE_DIR"
chmod 700 "$STATE_DIR"
ENV_FILE="$STATE_DIR/provisioning.env"
LOG_FILE="$STATE_DIR/provisioning.log"
touch "$ENV_FILE" "$LOG_FILE"
chmod 600 "$ENV_FILE" "$LOG_FILE"
KEYSTORE="$STATE_DIR/upload-keystore.p12"
CI_KEY="$STATE_DIR/vps-ci-deploy-key"

# record "..." - one line into the transcript, so a run that spans days leaves
# an account of itself. Names of things only, never values. This file is the
# subject of the "no secret in a log" rule, so anything passed to it has to be
# safe to read over somebody's shoulder.
record() { printf '%s  %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$1" >> "$LOG_FILE"; }

# is_done / mark_done - the state file, keyed by stage.
is_done()   { [[ -n "$(_existing "$1" || true)" ]]; }
mark_done() { write_env "$1" "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"; record "$1 done"; }

# skip_stage "Name" "why" - count a finished stage without clearing the screen,
# so a re-run reads as a list of what is left rather than a slideshow of what
# is not.
skip_stage() {
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '  %s✓%s Stage %s/%s · %s %s(already done: %s)%s\n' \
    "$GREEN" "$RESET" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$DIM" "$2" "$RESET"
  record "stage $_STAGE_INDEX skipped: $1"
}

# need TOOL "what it does here" - report a missing tool as a consequence rather
# than as a command not found halfway through a stage.
need() {
  if command -v "$1" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"
  else
    warn "$1 is missing: $2"
    SKIPPED+=("install $1")
  fi
}

# run CMD... - every side effect goes through here, which is what lets a dry run
# describe the procedure instead of performing it.
run() {
  if (( DRY_RUN )); then note "would run: $(printf '%q ' "$@")"; return 0; fi
  "$@"
}

# set_env_secret NAME VALUE - into this repository's protected environment, and
# never a repository-wide secret: ci.yml runs on pull requests from forks, and a
# fork must not be able to read a signing key. The value is never printed, not
# on success and not in gh's error output.
set_env_secret() {
  local name="$1" value="$2"
  if (( DRY_RUN )); then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ would set%s %s in the %s environment\n' "$GREEN" "$RESET" "$name" "$RELEASE_ENV"
    record "$name would be set in the $RELEASE_ENV environment"
    return
  fi
  if [[ -z "$value" ]]; then
    SKIPPED+=("$name (nothing was captured for it)")
    warn "nothing captured for $name; left to do"
    return
  fi
  if command -v gh >/dev/null 2>&1 &&
    printf '%s' "$value" | gh secret set "$name" --repo "$REPO" --env "$RELEASE_ENV" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s %s in the %s environment\n' "$GREEN" "$RESET" "$name" "$RELEASE_ENV"
    record "$name set in the $RELEASE_ENV environment"
    return
  fi
  SKIPPED+=("$name (gh secret set $name --repo $REPO --env $RELEASE_ENV)")
  warn "could not set $name; left to do"
}

# set_env_var NAME VALUE - the same environment, for a value that is not secret
# and is easier to check when it can be read back.
set_env_var() {
  local name="$1" value="$2"
  if (( DRY_RUN )); then
    printf '  %s✓ would set%s %s=%s in the %s environment\n' \
      "$GREEN" "$RESET" "$name" "$value" "$RELEASE_ENV"
    record "$name would be set in the $RELEASE_ENV environment"
    return
  fi
  if command -v gh >/dev/null 2>&1 &&
    gh variable set "$name" --body "$value" --repo "$REPO" --env "$RELEASE_ENV" >/dev/null 2>&1; then
    printf '  %s✓ set%s %s=%s in the %s environment\n' \
      "$GREEN" "$RESET" "$name" "$value" "$RELEASE_ENV"
    record "$name set in the $RELEASE_ENV environment"
    return
  fi
  SKIPPED+=("$name (gh variable set $name --repo $REPO --env $RELEASE_ENV)")
  warn "could not set $name; left to do"
}

# ── Reading the world back ─────────────────────────────────────────────────
#
# Each of these answers "is this already true?", which is what makes a re-run
# skip a stage on evidence rather than on a note it left itself. A dry run
# answers no to all of them, so it walks the whole procedure.

resolves_to() {
  if (( DRY_RUN )); then note "would check that $1 resolves to $2"; return 1; fi
  local answer
  if command -v dig >/dev/null 2>&1; then
    answer=$(dig +short "$1" | tail -n1)
  else
    answer=$(getent hosts "$1" | awk '{print $1}' | tail -n1)
  fi
  [[ -n "$answer" && "$answer" == "$2" ]]
}

release_env_exists() {
  if (( DRY_RUN )); then note "would check whether the $RELEASE_ENV environment exists"; return 1; fi
  command -v gh >/dev/null 2>&1 || return 1
  gh api "repos/$REPO/environments/$RELEASE_ENV" >/dev/null 2>&1
}

# gh lists secret names and never values, which is all a re-run needs to know.
env_secret_set() {
  if (( DRY_RUN )); then note "would check whether $1 is already set"; return 1; fi
  command -v gh >/dev/null 2>&1 || return 1
  gh secret list --repo "$REPO" --env "$RELEASE_ENV" 2>/dev/null |
    awk '{print $1}' | grep -qx "$1"
}

landing_deploy_ready() {
  if (( DRY_RUN )); then note "would check the landing repository's deploy credentials"; return 1; fi
  command -v gh >/dev/null 2>&1 || return 1
  gh secret list --repo "$LANDING_REPO" 2>/dev/null | awk '{print $1}' | grep -qx FTP_PASSWORD &&
    gh variable list --repo "$LANDING_REPO" 2>/dev/null | awk '{print $1}' | grep -qx FTP_SERVER_DIR
}

# The VPS address comes from the ssh alias rather than from a copy of the IP, so
# nothing here drifts if the box moves.
vps_field() {
  local value
  value=$(ssh -G "$VPS_ALIAS" 2>/dev/null | awk -v k="$1" '$1 == k {print $2}' | head -n1) || true
  [[ "$value" == "$VPS_ALIAS" ]] && return 1   # no such alias; ssh echoes the name back
  [[ -n "$value" ]] && printf '%s' "$value"
}

# ── A dry run performs nothing ─────────────────────────────────────────────
#
# The overrides are here rather than in the library above, which stays identical
# across every wizard. A hidden prompt with no answer becomes a value prefixed
# `dry-run-secret-`, and tests/provisioning.test.ts looks for that prefix in the
# output and in both files to prove nothing typed at one is echoed or stored.

if (( DRY_RUN )); then
  _dry() { printf '  %s[dry run]%s %s\n' "$YELLOW" "$RESET" "$1"; }
  open_url() { _dry "would open $1"; }
  pause()    { _dry "would wait: ${1:-Press Enter to continue}"; }
  confirm()  { _dry "would ask: $1 (taking yes)"; return 0; }
  # The library's own semantics, plus a newline the pipe would not get and a
  # marker. An unanswered prompt has to come back empty exactly as it does in a
  # real run, or a stage's own default never gets a chance to apply and the dry
  # run describes a procedure nobody would follow.
  ask() {
    local key="$1" prompt="$2" current input=""
    current=$(_existing "$key" || true)
    printf '  %s%s%s %s[dry run]%s\n' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    read -r input || true
    [[ -z "$input" && -n "$current" ]] && input="$current"
    printf -v "$key" '%s' "$input"
  }
  ask_secret() {
    local key="$1" prompt="$2" input=""
    printf '  %s%s%s %s[dry run, hidden]%s\n' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    read -rs input || true
    printf -v "$key" '%s' "${input:-dry-run-secret-$key}"
  }
fi

record "run started, dry run: $DRY_RUN"

banner "Gender Diary: the provisioning an agent cannot do"

# ── 1 ─────────────────────────────────────────────────────────────────────
if is_done PREFLIGHT; then
  skip_stage "What this needs, and where it writes" "recorded $(_existing PREFLIGHT)"
else
  stage "What this needs, and where it writes"
  say "Three destinations, and no others."
  say ""
  step "DNS records, at whoever answers for the parent domain."
  step "Secrets, in this repository's protected \"$RELEASE_ENV\" environment on GitHub."
  step "Everything that is not a secret, in:"
  note "    $ENV_FILE"
  say ""
  say "Nothing is written into the repository. It is public, and half of what"
  say "this captures is a credential. The transcript beside that file records"
  say "which stages ran and no values at all:"
  note "    $LOG_FILE"
  say ""
  say "The tools each stage needs:"
  need gh "sets the GitHub secrets. Without it, every secret below is left for you."
  need dig "reads DNS back, so a record is checked rather than assumed."
  need ssh "reads the $VPS_ALIAS alias for the VPS address."
  need ssh-keygen "makes the key CI deploys with."
  need keytool "makes the Android upload key. It ships with a JDK."
  need base64 "encodes the keystore for its GitHub secret."
  if (( DRY_RUN == 0 )) && command -v gh >/dev/null 2>&1 && ! gh auth status >/dev/null 2>&1; then
    warn "gh is installed but not logged in. Run: gh auth login"
  fi
  say ""
  say "Which repositories, so a secret cannot land in the wrong one. They are"
  say "deliberately separate: the landing site deploys with credentials this"
  say "repository has never seen, and the reverse (ADR-0019)."
  ask REPO "This repository [$REPO_DEFAULT]:"
  REPO="${REPO:-$REPO_DEFAULT}"
  ask LANDING_REPO "The landing site's repository [$LANDING_REPO_DEFAULT]:"
  LANDING_REPO="${LANDING_REPO:-$LANDING_REPO_DEFAULT}"
  say ""
  say "Stage 4 hands off to the landing repository's own wizard rather than"
  say "keeping a second copy of the lh.pl steps. It needs a checkout to run in."
  ask LANDING_DIR "Path to a landing-site checkout (blank if you have none):"
  write_env REPO "$REPO"
  write_env LANDING_REPO "$LANDING_REPO"
  write_env LANDING_DIR "$LANDING_DIR"
  mark_done PREFLIGHT
fi

# Whether stage 1 just asked or skipped, the rest of the run needs these.
REPO="$(_existing REPO || true)"; REPO="${REPO:-$REPO_DEFAULT}"
LANDING_REPO="$(_existing LANDING_REPO || true)"; LANDING_REPO="${LANDING_REPO:-$LANDING_REPO_DEFAULT}"
LANDING_DIR="$(_existing LANDING_DIR || true)"

# ── 2 ─────────────────────────────────────────────────────────────────────
if is_done RELEASE_ENVIRONMENT; then
  skip_stage "A protected environment to hold the release secrets" \
    "recorded $(_existing RELEASE_ENVIRONMENT)"
elif release_env_exists; then
  skip_stage "A protected environment to hold the release secrets" \
    "$RELEASE_ENV exists on $REPO"
else
  stage "A protected environment to hold the release secrets"
  say "Every secret this wizard captures is a release-time credential: the"
  say "Android signing key, the Play upload credential, the key that deploys the"
  say "Journal. None of them belongs to the checks that run on a pull request."
  say ""
  say "That is the whole reason for an environment rather than repository-wide"
  say "secrets. ci.yml is given no secret at all and runs on pull requests,"
  say "including from forks. release.yml is the only job that declares"
  say "\"environment: $RELEASE_ENV\", so it is the only job that can read these."
  say "Repository-wide secrets would undo that in one click."
  open_url "https://github.com/$REPO/settings/environments"
  step "New environment, named exactly: $RELEASE_ENV"
  step "Add yourself as a required reviewer, so a publish is a decision."
  step "Under deployment branches and tags, allow only the tag pattern v*."
  note "The tag rule matters: release.yml runs on a v* tag, and a workflow"
  note "reaching this environment from a branch would be a signed release built"
  note "from something nobody tagged."
  pause "Created, with the reviewer and the tag rule?"
  if release_env_exists || confirm "Record it as done?"; then
    mark_done RELEASE_ENVIRONMENT
  else
    SKIPPED+=("the $RELEASE_ENV environment on $REPO")
  fi
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
if is_done DNS_JOURNAL; then
  skip_stage "DNS for the Journal's own origin" "recorded $(_existing DNS_JOURNAL)"
else
  stage "DNS for the Journal's own origin"
  say "The Journal is served from $JOURNAL_ORIGIN and from nowhere else."
  say "Browser storage attaches to that origin, which is why it was decided in"
  say "ticket 01 and cannot be moved afterwards: a Journal created there and"
  say "then moved is a Journal nothing links to (ADR-0019)."
  say ""
  say "The record has to resolve before anything else on the box is worth"
  say "trying. Ticket 05's certbot run answers an HTTP challenge on this name,"
  say "and it fails while the name points nowhere."
  say ""
  VPS_HOST=$(vps_field hostname) || VPS_HOST=""
  if [[ -n "$VPS_HOST" ]]; then
    say "The VPS answers at $VPS_HOST, read from the $VPS_ALIAS ssh alias."
  else
    warn "No $VPS_ALIAS alias in your ssh config, so the address has to be typed."
    ask VPS_HOST "The VPS public IP:"
  fi
  say ""
  step "Open the DNS panel that actually answers for the parent domain, which"
  say "    is not always the registrar. The parent is already split: the apex"
  say "    is on shared hosting and a sibling subdomain is an A record to this"
  say "    VPS, so this is one more record of the same kind."
  step "Add an A record for the Journal's subdomain pointing at $VPS_HOST."
  pause "Press Enter once the record is saved."
  if resolves_to "$JOURNAL_ORIGIN" "$VPS_HOST"; then
    say "$JOURNAL_ORIGIN resolves to $VPS_HOST."
    mark_done DNS_JOURNAL
  elif confirm "It does not resolve yet. Record it as done and move on?"; then
    mark_done DNS_JOURNAL
    note "Records take a while to spread. Check with: dig +short $JOURNAL_ORIGIN"
  else
    SKIPPED+=("the A record for $JOURNAL_ORIGIN pointing at $VPS_HOST")
  fi
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
if is_done DNS_AND_HOSTING_LANDING; then
  skip_stage "The landing site's origin and its deploy" \
    "recorded $(_existing DNS_AND_HOSTING_LANDING)"
elif landing_deploy_ready; then
  skip_stage "The landing site's origin and its deploy" \
    "$LANDING_REPO already holds its FTP credentials"
else
  stage "The landing site's origin and its deploy"
  say "The site lives at $LANDING_ORIGIN, on shared hosting, in its own"
  say "repository, with its own credentials. That separation is the decision in"
  say "ADR-0019 rather than an accident of who set up what: a marketing"
  say "dependency or a bad deploy must not be able to reach the origin holding"
  say "somebody's Journal."
  say ""
  say "So this stage checks the state and hands over. $LANDING_REPO ships its"
  say "own wizard, scripts/lhpl-setup.sh, which maps the domain to a directory"
  say "on the account, issues the certificate, and sets the three FTP secrets"
  say "its deploy workflow reads. A second copy of those steps here would drift"
  say "from the one that is live, and would put this repository's session in"
  say "reach of the other repository's credentials."
  say ""
  if [[ -n "$LANDING_DIR" && -x "$LANDING_DIR/scripts/lhpl-setup.sh" ]]; then
    say "Found it at $LANDING_DIR/scripts/lhpl-setup.sh"
    if confirm "Run it now? This wizard picks up again afterwards."; then
      if (( DRY_RUN )); then
        note "would run scripts/lhpl-setup.sh in $LANDING_DIR"
      elif ! (cd "$LANDING_DIR" && ./scripts/lhpl-setup.sh); then
        warn "it exited non-zero; finish it in that checkout before ticking anything"
      fi
    fi
  else
    warn "No landing checkout to run it from."
    step "Clone $LANDING_REPO, then run scripts/lhpl-setup.sh inside it."
  fi
  if landing_deploy_ready || confirm "Record the landing side as done?"; then
    mark_done DNS_AND_HOSTING_LANDING
  else
    SKIPPED+=("the landing site: run scripts/lhpl-setup.sh in $LANDING_REPO")
  fi
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
if is_done VPS_DEPLOY_ACCESS; then
  skip_stage "The key CI deploys the Journal with" "recorded $(_existing VPS_DEPLOY_ACCESS)"
elif env_secret_set VPS_DEPLOY_KEY; then
  skip_stage "The key CI deploys the Journal with" \
    "VPS_DEPLOY_KEY is already in the $RELEASE_ENV environment"
else
  stage "The key CI deploys the Journal with"
  say "The Journal is a static bundle, so the runner can build it and ship the"
  say "result over ssh. That needs a key of its own, held in the $RELEASE_ENV"
  say "environment: never the personal key in your ssh config. A CI-only key is"
  say "one line to revoke in one authorized_keys file, and it never had push"
  say "access to anything."
  say ""
  say "What reads these four: ticket 05's deploy step. It publishes a release"
  say "directory and flips a symlink, so the account below needs to write under"
  say "the Journal's own home directory and restart nothing else on the box."
  say ""
  VPS_HOST=$(vps_field hostname) || VPS_HOST=""
  VPS_PORT=$(vps_field port) || VPS_PORT=""
  if [[ -n "$VPS_HOST" ]]; then
    say "Host and port come from the $VPS_ALIAS alias: $VPS_HOST on $VPS_PORT."
  else
    ask VPS_HOST "The VPS public IP:"
    ask VPS_PORT "Its ssh port:"
  fi
  say ""
  say "One system user per site on that box, so a compromise of one app cannot"
  say "touch another's files. zabka-stats has its own; the Journal needs its"
  say "own too. Ticket 05 creates the user, its home directory and the nginx"
  say "server block. This stage only arranges the key it will log in with."
  ask VPS_USER "The Journal's system user on the VPS [journal]:"
  VPS_USER="${VPS_USER:-journal}"
  write_env VPS_USER "$VPS_USER"
  say ""
  if [[ -f "$CI_KEY" ]]; then
    say "Reusing the key already at $CI_KEY"
  else
    say "Making one, with no passphrase, because CI cannot type one:"
    run ssh-keygen -t ed25519 -N "" -C "github-actions deploy for $JOURNAL_ORIGIN" -f "$CI_KEY"
    run chmod 600 "$CI_KEY"
  fi
  say ""
  say "Install the public half for $VPS_USER on the box. From an account that"
  say "can sudo there:"
  if [[ -f "$CI_KEY.pub" ]]; then
    say ""
    say "$(cat "$CI_KEY.pub")"
    say ""
  fi
  note "  sudo install -d -m 700 -o $VPS_USER -g $VPS_USER /home/$VPS_USER/.ssh"
  note "  sudo tee -a /home/$VPS_USER/.ssh/authorized_keys   # paste the line above"
  note "  sudo chown $VPS_USER:$VPS_USER /home/$VPS_USER/.ssh/authorized_keys"
  note "  sudo chmod 600 /home/$VPS_USER/.ssh/authorized_keys"
  pause "Press Enter once it is in place."
  if (( DRY_RUN )); then
    note "would try: ssh -i $CI_KEY -p $VPS_PORT $VPS_USER@$VPS_HOST true"
  elif ssh -i "$CI_KEY" -p "${VPS_PORT:-22}" -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
    "$VPS_USER@$VPS_HOST" true >/dev/null 2>&1; then
    say "The key logs in as $VPS_USER."
  else
    warn "The key does not log in yet. The secrets below are still worth setting,"
    warn "but ticket 05's deploy will fail until it does."
  fi
  set_env_secret VPS_HOST "$VPS_HOST"
  set_env_secret VPS_PORT "$VPS_PORT"
  set_env_secret VPS_USER "$VPS_USER"
  if [[ -f "$CI_KEY" ]]; then
    set_env_secret VPS_DEPLOY_KEY "$(cat "$CI_KEY")"
  else
    set_env_secret VPS_DEPLOY_KEY ""
  fi
  say ""
  note "The private half stays at $CI_KEY, mode 600, outside the repository."
  note "Once a deploy has worked you can delete it: GitHub keeps the only copy"
  note "CI needs, and a lost key is one ssh-keygen and one authorized_keys line."
  if env_secret_set VPS_DEPLOY_KEY || confirm "Record the VPS access as done?"; then
    mark_done VPS_DEPLOY_ACCESS
  else
    SKIPPED+=("deploy access to the VPS for $VPS_USER")
  fi
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
if is_done PLAY_ACCOUNT; then
  skip_stage "A Google Play developer account, and the app record" \
    "recorded $(_existing PLAY_ACCOUNT)"
else
  stage "A Google Play developer account, and the app record"
  say "Start this before ticket 18 has anything to upload. Registration is paid"
  say "and identity-verified, and the verification is not instant, so it is the"
  say "one step here that can hold up a release by days rather than minutes."
  say ""
  say "The application ID is $ANDROID_APP_ID and there is nothing to type: it"
  say "comes out of the manifest in the first bundle you upload. Which is also"
  say "why it was decided in ticket 01. After that first upload, changing it"
  say "publishes a second app rather than an update, and every installed copy"
  say "stops receiving updates (ADR-0019)."
  open_url "https://play.google.com/console/signup"
  step "Register, pay the one-off fee, and complete identity verification."
  step "Create the app. Name and default language can change later."
  step "Read what the console says about reaching production: a new personal"
  say "    account may have a closed-testing requirement to satisfy first. Take"
  say "    the console's current wording over anything written here."
  warn "Aurora installs the same Play package rather than a build of its own, so"
  warn "there is no second listing to create for it."
  pause "Account registered and the app created?"
  if confirm "Record the Play account and app as done?"; then
    mark_done PLAY_ACCOUNT
  else
    SKIPPED+=("the Google Play account and the app record for $ANDROID_APP_ID")
  fi
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
if is_done PLAY_DELIVERY; then
  skip_stage "The credential a release uploads to Play with" \
    "recorded $(_existing PLAY_DELIVERY)"
elif env_secret_set PLAY_SERVICE_ACCOUNT_JSON; then
  skip_stage "The credential a release uploads to Play with" \
    "PLAY_SERVICE_ACCOUNT_JSON is already in the $RELEASE_ENV environment"
else
  stage "The credential a release uploads to Play with"
  say "Ticket 18 delivers the App Bundle from inside the $RELEASE_ENV"
  say "environment, which means it cannot log in as you. It needs a service"
  say "account: an identity Google issues to the project, with a JSON key, that"
  say "you grant release permission to in the console."
  say ""
  say "Two halves in two places, and the console's menu names move, so follow"
  say "the console's own link rather than a path written down here."
  open_url "https://console.cloud.google.com/iam-admin/serviceaccounts"
  step "Create a service account, then add a key of type JSON and download it."
  open_url "https://play.google.com/console/developers/api-access"
  step "Link that service account, and grant it release access to the app."
  say ""
  say "The file goes straight into the environment. It is never copied into the"
  say "repository, and it is worth deleting from your downloads afterwards: it"
  say "is a key that can publish to your store listing."
  ask PLAY_KEY_PATH "Path to the downloaded JSON (blank to skip):"
  PLAY_KEY_JSON=""
  if [[ -n "$PLAY_KEY_PATH" && -f "${PLAY_KEY_PATH/#\~/$HOME}" ]]; then
    PLAY_KEY_JSON=$(cat "${PLAY_KEY_PATH/#\~/$HOME}")
  elif (( DRY_RUN )); then
    PLAY_KEY_JSON="dry-run-secret-PLAY_SERVICE_ACCOUNT_JSON"
  elif [[ -n "$PLAY_KEY_PATH" ]]; then
    warn "No file at $PLAY_KEY_PATH"
  fi
  set_env_secret PLAY_SERVICE_ACCOUNT_JSON "$PLAY_KEY_JSON"
  if [[ -f "${PLAY_KEY_PATH/#\~/$HOME}" ]] && confirm "Shred the downloaded copy now?"; then
    if command -v shred >/dev/null 2>&1; then
      run shred -u "${PLAY_KEY_PATH/#\~/$HOME}"
    else
      run rm -f "${PLAY_KEY_PATH/#\~/$HOME}"
    fi
  fi
  if env_secret_set PLAY_SERVICE_ACCOUNT_JSON || confirm "Record the Play credential as done?"; then
    mark_done PLAY_DELIVERY
  else
    SKIPPED+=("PLAY_SERVICE_ACCOUNT_JSON in the $RELEASE_ENV environment")
  fi
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
if is_done ANDROID_UPLOAD_KEY; then
  skip_stage "The Android signing key, and where it lives" \
    "recorded $(_existing ANDROID_UPLOAD_KEY)"
else
  stage "The Android signing key, and where it lives"
  say "One key signs every release build of $ANDROID_APP_ID. Read what that"
  say "means before generating it, because two of the consequences are"
  say "permanent:"
  say ""
  step "For the APK channels - the release APK on GitHub, which Obtainium"
  say "    follows, and F-Droid - this key is the app's identity. An installed"
  say "    copy will not accept an update signed by a different one. Losing it"
  say "    means everyone reinstalls and restores from an Archive."
  step "For Play, this is the upload key. That one Google can reset, at the"
  say "    cost of a support round trip."
  say ""
  warn "So: back the keystore file up somewhere offline, and keep the password"
  warn "in your password manager. GitHub secrets are write-only. Neither this"
  warn "wizard nor GitHub can ever show you the password again."
  say ""
  say "Where things go. The keystore is a file at:"
  note "  $KEYSTORE"
  say "and, base64-encoded, a secret in the $RELEASE_ENV environment, because"
  say "that is the only job allowed to sign. Ticket 18 reads it from there."
  say "Neither the file nor the password goes anywhere near the repository."
  say ""
  KEYSTORE_ALIAS="upload"
  KEYSTORE_PASSWORD=""
  if [[ -f "$KEYSTORE" ]]; then
    say "A keystore is already at that path. It is never regenerated: a second"
    say "key is a second app, so this only confirms the password and re-sets the"
    say "secrets."
    say ""
    if (( DRY_RUN == 0 )) && command -v secret-tool >/dev/null 2>&1; then
      KEYSTORE_PASSWORD=$(secret-tool lookup service gender-diary keystore "$KEYSTORE" || true)
      if [[ -n "$KEYSTORE_PASSWORD" ]]; then say "Password found in your wallet."; fi
    fi
    attempt=0
    while [[ -z "$KEYSTORE_PASSWORD" ]] && (( attempt < 3 )); do
      attempt=$((attempt + 1))
      ask_secret KEYSTORE_PASSWORD "Its password:"
      if (( DRY_RUN )); then break; fi
      if KEYSTORE_PASSWORD="$KEYSTORE_PASSWORD" keytool -list -keystore "$KEYSTORE" \
        -storetype PKCS12 -storepass:env KEYSTORE_PASSWORD >/dev/null 2>&1; then
        break
      fi
      warn "That does not open the keystore."
      KEYSTORE_PASSWORD=""
    done
  else
    say "The password is asked for rather than generated, so that the copy you"
    say "can recover from exists before the key does. Put one in your password"
    say "manager now, then paste it here."
    say ""
    attempt=0
    until (( attempt >= 3 )); do
      attempt=$((attempt + 1))
      ask_secret KEYSTORE_PASSWORD "Password for the new keystore:"
      ask_secret KEYSTORE_PASSWORD_AGAIN "The same again:"
      if (( DRY_RUN )); then break; fi
      if [[ ${#KEYSTORE_PASSWORD} -lt 12 ]]; then
        warn "Twelve characters or more, please. This one signs releases for years."
      elif [[ "$KEYSTORE_PASSWORD" != "$KEYSTORE_PASSWORD_AGAIN" ]]; then
        warn "The two do not match."
      else
        break
      fi
      KEYSTORE_PASSWORD=""
    done
    if [[ -n "$KEYSTORE_PASSWORD" ]]; then
      # PKCS12 keeps one password for the store and the key, which is one fewer
      # value to lose. -storepass:env keeps it out of the process list, where a
      # command line would have put it for anyone on the machine to read.
      KEYSTORE_PASSWORD="$KEYSTORE_PASSWORD" run keytool -genkeypair \
        -keystore "$KEYSTORE" -storetype PKCS12 \
        -storepass:env KEYSTORE_PASSWORD \
        -alias "$KEYSTORE_ALIAS" -keyalg RSA -keysize 4096 -validity 10950 \
        -dname "CN=Gender Diary, OU=Gender Diary, O=Gender Diary, C=PL"
      run chmod 600 "$KEYSTORE"
    else
      warn "No password, so no key. Re-run this stage when you have one ready."
    fi
  fi
  if [[ -n "${KEYSTORE_PASSWORD:-}" ]] && command -v secret-tool >/dev/null 2>&1 &&
    confirm "Also keep the password in your wallet, so a re-run need not ask?"; then
    if (( DRY_RUN )); then
      note "would store the keystore password in the wallet"
    else
      printf '%s' "$KEYSTORE_PASSWORD" | secret-tool store \
        --label="Gender Diary Android upload keystore" \
        service gender-diary keystore "$KEYSTORE" || warn "the wallet refused it"
    fi
  fi
  if [[ -f "$KEYSTORE" ]] && (( DRY_RUN == 0 )); then
    say ""
    say "The certificate this key presents, which Play shows too and which is"
    say "how you check that the right key signed a build:"
    KEYSTORE_PASSWORD="${KEYSTORE_PASSWORD:-}" keytool -list -v -keystore "$KEYSTORE" \
      -storetype PKCS12 -storepass:env KEYSTORE_PASSWORD 2>/dev/null |
      grep -i 'SHA256:' | head -n1 || true
  fi
  say ""
  if [[ -f "$KEYSTORE" ]]; then
    set_env_secret ANDROID_KEYSTORE_BASE64 "$(base64 -w0 < "$KEYSTORE")"
  elif (( DRY_RUN )); then
    set_env_secret ANDROID_KEYSTORE_BASE64 "dry-run-secret-ANDROID_KEYSTORE_BASE64"
  fi
  set_env_secret ANDROID_KEYSTORE_PASSWORD "${KEYSTORE_PASSWORD:-}"
  set_env_var ANDROID_KEY_ALIAS "$KEYSTORE_ALIAS"
  unset KEYSTORE_PASSWORD KEYSTORE_PASSWORD_AGAIN
  say ""
  note "Ticket 18 decodes the keystore into the runner, signs with it inside the"
  note "$RELEASE_ENV environment, and never writes it anywhere a job artifact or"
  note "a log can reach. docs/provisioning.md names all three values."
  if env_secret_set ANDROID_KEYSTORE_BASE64 || confirm "Record the signing key as done?"; then
    mark_done ANDROID_UPLOAD_KEY
  else
    SKIPPED+=("the Android upload key and its secrets")
  fi
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
if is_done FDROID_SUBMISSION; then
  skip_stage "F-Droid, and what it is waiting for" "recorded $(_existing FDROID_SUBMISSION)"
else
  stage "F-Droid, and what it is waiting for"
  say "F-Droid does not accept a build. It rebuilds the published source itself,"
  say "with a dependency graph it can build freely, and signs what it built. So"
  say "there is nothing to provision here and no credential to capture, and the"
  say "submission is only worth filing once three things exist. All three are"
  say "ticket 18's:"
  say ""
  step "An Android project that builds from a clean public checkout."
  step "Localized metadata committed under fastlane/metadata/android/."
  step "A recorded reproducibility attempt against the signed release APK, and"
  say "    a decision written down if the F-Droid signature cannot be"
  say "    update-compatible with the APK people already have."
  say ""
  FDROID_READY=1
  [[ -d android ]] || { warn "no android/ project yet (ticket 11 and 18)"; FDROID_READY=0; }
  [[ -d fastlane/metadata/android ]] || { warn "no fastlane/metadata/android/ yet (ticket 18)"; FDROID_READY=0; }
  if (( FDROID_READY )); then
    say "Both are present, so the request is worth filing."
    open_url "https://gitlab.com/fdroid/rfp/-/issues"
    step "File a request for packaging naming the public repository and the"
    say "    tagged release the metadata describes."
    if confirm "Filed?"; then
      mark_done FDROID_SUBMISSION
    else
      SKIPPED+=("the F-Droid request for packaging")
    fi
  else
    say "Nothing is recorded, deliberately, so the next run checks again rather"
    say "than skipping a step that was never taken. This is the one stage a"
    say "re-run always walks."
    SKIPPED+=("F-Droid, once ticket 18 has metadata and a reproducibility result")
  fi
fi

record "run finished"

say ""
say "What reads what is in docs/provisioning.md. Two tickets are waiting on"
say "this: ticket 05 for the DNS record and the VPS key, ticket 18 for the"
say "signing key and the Play credential."
if (( DRY_RUN )); then
  say ""
  warn "This was a dry run. Nothing above happened, and the state file it wrote"
  warn "is a throwaway under /tmp, so a second dry run walks everything again."
  note "To watch a dry run skip its own stages, give it a directory that lasts:"
  note "  GENDER_DIARY_STATE_DIR=/tmp/gd-dry DRY_RUN=1 scripts/provision.sh"
fi

finish
